---
roles:
  - name: cloudalchemy.node-exporter
    version: 0.19.0
  - name: cloudalchemy.coredns
    version: 0.3.2
## currently using our own fork
#  - name: n0emis.bigbluebutton
  - name: geerlingguy.nodejs
    version: 5.1.1
  - name: geerlingguy.docker
    version: 2.7.0
  - name: geerlingguy.redis
    version: 1.6.0
  - name: geerlingguy.postgresql
    version: 2.2.0
  - name: geerlingguy.ruby
    version: 2.6.0
  - name: cloudalchemy.prometheus
    version: 2.15.0
  - name: cloudalchemy.grafana
    version: 0.17.0
