{
 "title": "BigBlueButton All Servers",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bbb_api_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BBB API",
   "type": "stat",
   "gridPos": { "h": 26, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "A",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "bbb_api_up",
     "legendFormat": "{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    { "expr": "bbb_meetings_participants", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Voice Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_voice_participants",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Video Participants",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_video_participants",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Max Participants", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "expr": "bbb_meetings_participants", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Max Video Participants", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "bbb_meetings_video_participants",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Current Meetings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 },
   "targets": [
    { "expr": "bbb_meetings_participants", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "API 95-th Percentile Latency",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short", "label": "Latency [s]" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getMeetings\"}[5m])) by (le, instance))",
       "legendFormat": "{{instance}} - getMeetings"
      }
     ]
    }
   ]
  }
 ]
}