{
 "title": "Cockpit",
 "description": "Fuer Leute mit wenig Beinfreiheit",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Zusammenfassung",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(bbb_meetings)", "legendFormat": "Meetings" },
    { "expr": "sum(bbb_meetings_participants)", "legendFormat": "Teilnehmende" },
    {
     "expr": "sum(bbb_meetings_video_participants)",
     "legendFormat": "Videos"
    }
   ]
  },
  {
   "title": "Aktueller Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(bbb_meetings_participants)", "legendFormat": "Teilnehmende" },
    { "expr": "sum(bbb_meetings)", "legendFormat": "Meetings" },
    {
     "expr": "sum(bbb_meetings_video_participants)",
     "legendFormat": "Videoteilnehmende"
    }
   ]
  },
  {
   "title": "Maximum bisher",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sum(bbb_meetings_participants)", "legendFormat": "Teilnehmende" },
    { "expr": "sum(bbb_meetings)", "legendFormat": "Meetings" },
    {
     "expr": "sum(bbb_meetings_video_participants)",
     "legendFormat": "Videoteilnehmende"
    }
   ]
  },
  {
   "title": "Drehzahl",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bbb_meetings_participants", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Video Participants",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_meetings_video_participants",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}