---
- name: ensure default recording is disabled
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: '^disableRecordingDefault'
    line: 'disableRecordingDefault=true'
  notify: restart bigbluebutton

- name: ensure recording auto start is disabled
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: '^autoStartRecording'
    line: 'autoStartRecording=false'
  notify: restart bigbluebutton

- name: ensure users are not allowed to start recording
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: '^allowStartStopRecording'
    line: 'allowStartStopRecording=false'
  notify: restart bigbluebutton

- name: ensure http call to root is redirected
  copy:
    content: |
      location = / {
        return 301 '{{bbb_url}}';
      }
    mode: 0755
    dest: /etc/bigbluebutton/nginx/redirectroot.nginx
  notify: reload nginx

- name: ensure nginx is enabled
  systemd:
    name: nginx
    enabled: yes
    masked: no

- name: ensure our own default slides are used
  copy:
    src: default.pdf
    dest: /var/www/bigbluebutton-default/default.pdf

- name: copy our own mute/unmute sounds
  copy:
    src: '{{ item }}'
    dest: '/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/{{item}}'
  with_items:
    - conf-muted-ulmlernt.wav
    - conf-unmuted-ulmlernt.wav

- name: ensure our own mute sound is used
  xml:
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml
    xpath: '/configuration/profiles/profile[@name="cdquality"]/param[@name="muted-sound"]'
    attribute: value
    value: conference/conf-muted-ulmlernt.wav
  notify: restart bigbluebutton

- name: ensure our own unmute sound is used
  xml:
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml
    xpath: '/configuration/profiles/profile[@name="cdquality"]/param[@name="unmuted-sound"]'
    attribute: value
    value: conference/conf-unmuted-ulmlernt.wav
  notify: restart bigbluebutton

- name: adapt coturn ports in ufw
  copy:
    content: |
      [turnserver]
      title=Coturn turnserver
      description=Free open source implementation of TURN and STUN Server
      ports=3478,3479,5349,5350/tcp|3478,3479,5349,5350,49152:65535/udp
    mode: 0644
    dest: /etc/ufw/applications.d/turnserver

- name: allow turnserver in ufw
  ufw:
    rule: allow
    name: turnserver
    state: enabled

- name: adapt freeswitch ports in ufw
  copy:
    content: |
      [freeswitch]
      title=freeswitch
      description=freeswitch telecom stack
      ports=16384:32768/udp
    mode: 0644
    dest: /etc/ufw/applications.d/freeswitch

- name: allow freeswitch in ufw
  ufw:
    rule: allow
    name: freeswitch
    state: enabled


- name: Ensure coturn is restarted everyday @ 4 am
  cron:
    name: "restart coturn"
    minute: "0"
    hour: "4"
    user: root
    job: "systemctl restart coturn.service"

