---
- name: Ensure Docker Key is removed
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: absent

- name: Ensure Docker Repository is absent
  apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items:
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"

- name: Ensure Docker is not installed
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: absent

- name: Ensure Docker group is deleted
  group:
    name: docker
    state: absent

- name: check if docker network interface exists
  shell: ip a | grep docker
  register: docker_network_interface

- name: Ensure Docker network interface is deleted
  command: ip link delete docker0 
  when: docker_network_interface.rc == 0
