---
- name: Ensure ufw and fail2ban packages
  apt:
    name:
      - ufw
      - fail2ban
    state: present

- name: Allow ssh in ufw
  ufw:
    rule: allow
    name: OpenSSH
 
- name: Allow everything out 
  ufw:
    direction: outgoing
    policy: allow

- name: Allow default nothing in and enable UFW
  ufw:
    direction: incoming
    policy: deny
    state: enabled

- name: ensure fail2ban uses ufw
  copy:
    content: |
      [DEFAULT]
      banaction = ufw
    mode: 0644
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban
