---
- name: Ensure 'ssl-cert' group exists
  group:
    name: ssl-cert
    state: present

# fixed for ubuntu 2004
# - name: Add certbot apt repo
#   apt_repository:
#     repo: ppa:certbot/certbot
#     state: present

- name: Install certbot
  apt:
    pkg:
      - certbot
    update_cache: true
    state: present

- name: Ensure Let's Encrypt API uses v2
  lineinfile:
    path: /etc/letsencrypt/cli.ini
    line: 'server = https://acme-v02.api.letsencrypt.org/directory'

- name: Ensure Let's Encrypt Directories are owned by ssl-cert group
  file:
    path: "{{ item }}"
    recurse: yes
    group: ssl-cert
    mode: g+rx
  with_items:
    - /etc/letsencrypt/live
    - /etc/letsencrypt/archive
    - /etc/letsencrypt/keys

- name: Register certbot certificate file
  stat:
    path: "/etc/letsencrypt/live/{{ turn_hostname }}/fullchain.pem"
  register: certbot_certificate_file_path

- name: Generate Certificates
  command: certbot certonly -d {{ turn_hostname }} -d {{ ansible_fqdn }} --agree-tos --email {{ letsencrypt_email }} --standalone
  when: not certbot_certificate_file_path.stat.exists

- name: Ensure Let's Encrypt Certificate and Keys are owned by ssl-cert group and readable
  file:
    path: "{{ item }}"
    mode: 'u=rw,g=r'
    group: ssl-cert
  with_items:
    - /etc/letsencrypt/archive/{{ turn_hostname }}/privkey1.pem
